// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the Luut SLU marketplace catalog for active seller products by keyword and/or category.",
  inputSchema: {
    query: z.string().optional().describe("Keyword to match in product name or description."),
    category: z.string().optional().describe("Filter by category (e.g. Beanies, Hoodies)."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const sb = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    let q = sb.from("seller_products").select("id, name, price, category, location, description, seller_id").eq("status", "active").limit(limit ?? 20);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.ilike("category", category);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sellers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_sellers_default = defineTool2({
  name: "list_sellers",
  title: "List sellers",
  description: "List approved sellers on Luut SLU, optionally filtered by location.",
  inputSchema: {
    location: z2.string().optional().describe("Filter by seller location (e.g. Castries)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results, default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ location, limit }) => {
    const sb = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
    let q = sb.from("seller_profiles").select("id, seller_name, location, categories, storefront_slug").eq("is_approved", true).limit(limit ?? 20);
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { sellers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-platform-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_platform_info_default = defineTool3({
  name: "get_platform_info",
  title: "Get platform info",
  description: "Return static facts about Luut SLU: payment model, meetup locations, categories, currency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify(
          {
            name: "Luut SLU",
            country: "Saint Lucia",
            currency: "XCD (EC$)",
            paymentModel: "Pay on Meetup \u2014 cash at safe locations",
            meetupLocations: ["Castries", "Gros Islet", "Vieux Fort", "Rodney Bay"],
            categories: [
              "Beanies",
              "Hats",
              "Ski Masks",
              "Shirts/Tops",
              "Hoodies/Outerwear",
              "Pants/Bottoms",
              "Shorts",
              "Shoes/Footwear",
              "Bags/Backpacks",
              "Accessories",
              "Jewelry",
              "Watches",
              "Sunglasses"
            ],
            website: "https://luut-slu-supply.lovable.app"
          },
          null,
          2
        )
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "luut-slu-mcp",
  title: "Luut SLU Marketplace",
  version: "0.1.0",
  instructions: "Tools for the Luut SLU marketplace (Saint Lucia). Use `search_products` to browse the catalog, `list_sellers` to discover verified sellers, and `get_platform_info` for payment/meetup/currency facts.",
  tools: [search_products_default, list_sellers_default, get_platform_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
